default:
  image: docker:25.0.3-dind   # Using Docker-in-Docker image
  before_script:
    - dockerd -l fatal &      # Start Docker daemon in background
    - sleep 5                 # Wait for Docker daemon to initialize
  tags:
    - arm64-runner            # Specify the runner tag

# Global variables for the pipeline
variables:
  # Kubernetes resource requests
  KUBERNETES_CPU_REQUEST: 60
  KUBERNETES_MEMORY_REQUEST: 256G
  KUBERNETES_EPHEMERAL_STORAGE_REQUEST: 2T


build:
  stage: build
  before_script:
    - apk add --update curl && apk add --update git tar unzip zip && rm -rf /var/cache/apk/*
    - dockerd -l fatal &
    # - docker login -u "$ART_DOCKER_USER" -p "$ART_DOCKER_PASS" $ART_DOCKER_REG
    # Installing JFrog CLI
    - curl -fL https://install-cli.jfrog.io | sh
    - chmod +x /usr/local/bin/jf
    # Configure artifactory instance with JFrog CLI
    - pwd
    - projFolder=$(pwd)
    - /usr/local/bin/jf --version
    - /usr/local/bin/jf c add artifactory-server --url=$ART_PLAT_URL --user=$ART_PLAT_USER --password=$ART_PLAT_PASS
    - /usr/local/bin/jf rt ping

  script:


    # Variables
    - BRANCH="20260529-1"
    - ARCH="ARM"
    - KERNAL_TAG="qcom-next-7.1-rc4-20260524"
    - DOCKER_TAG="glymero-builder"
    - SNAPSHOT="20260528"
    - DTB="qcom/glymur-crd.dtb"
    - PR="422"
    - USER=lnxbuild
    - UID=2366345
    - GID=2366345
    - WORK_DIR="/home/${USER}/app"

    # Docker Build & Run
    - docker build --network=host --build-arg USER=${USER} --build-arg UID=${UID} --build-arg GID=${GID} --no-cache -t ${DOCKER_TAG} .
    - docker run --network=host -v $(pwd):${WORK_DIR} glymero-builder -b ${BRANCH} -k ${KERNAL_TAG} -s ${SNAPSHOT} -d ${DTB} -p ${PR} -w ${WORK_DIR} -x false
    - mkdir -p /images
    - docker cp build:${WORK_DIR}/${DOCKER_TAG}/qcom-deb-images/deb_artifacts.tar /images
    - ls /images

    # Define a reusable function for artifacts copy & zip it and upload to artifactory
    # This reduces code duplication and improves maintainability
    - docker rm build
